### ISSUE TITLE
Making codectrl better for development.

### ISSUE THREAD

**Issue by svmorris** [Authentura/codectrl#24]
This issue technically should be on each logging library but I think it would be messy having re-creating it on 5 different repositories.

I have been recently doing some development and trying to use codectrl to see if it could be usable for coding. One thing would be nice if we could handle debug modes within the library. By this I mean is that we could add an extra function (maybe call it `dbg`) that checks for a `DEBUG` environment variable. If it is set to true then it just calls the standard log function. This would be great as you could just leave log calls in your code where you want to debug them, and not worry about the inefficiency of making lots of requests to endpoints that don't exist.

I do want to make it clear that I think having two separate functions would be useful, because on the research side of things I would rather have the program warn me / crash if logging doesn't work.

**Comment by svmorris** [comment]
If @STBoyden  you agree that this is a good idea then ill go implement it in the python one.

**Comment by STBoyden** [comment]
Yeah go ahead. I can get started on the others too.

**Comment by svmorris** [comment]
I wrote back on slack, im not sure if you saw. We should come up with some universal implementation of this and im not sure exactly how.

I like your idea of using some sort of lamda(or something similar) function, but I don't want users to have to pass an extra argument at each call. So we how do you think its best to implement this?

**Comment by STBoyden** [comment]
> I like your idea of using some sort of lamda (or something similar) function, but I don't want users to have to pass an extra argument at each call. So we how do you think its best to implement this?

It would need to take some sort of extra argument to know what to check for, unless we replace the message with it? Or both? 

Because for Rust I was thinking of a macro or something like this:

```rust
Codectrl::log_if(|| some_condition, "Message");
```

Or a macro thing like:
```rust
Codectrl::log!("Message"); // like we had before
Codectrl::log!(|| some_condition, "Message"); // like the new thing
```

**Comment by svmorris** [comment]
I mean I was mostly just hoping we could do it without passing anything extra to it, which is why I was thinking of env variables. Although I do see the point of what you are saying that it could be a lot more versatile, I strongly believe that the default should be as simple as possible. 
Would you be opposed to doing both? As they are just a couple line wrappers around the log function we could have a `dbg` that looks for `env DEBUG` and a `log_if` that looks for a condition. Furthermore if we are not too opposed to ambiguity then in languages that support it we could just use `env DEBUG` if there is no condition passed.

I am less certain about the ambiguity part as it can cause a lot of odd errors as we saw in log4j.


I feel like it would be good if we could do both. Especially in languages that support optional arguments we could perhaps only check the debug variable if no condition is set.
My problem with t

**Comment by STBoyden** [comment]
Both might be fine, I'm just concerned about polluting `env`s with even more environment variables. Also I probably wouldn't call the function `dbg` as that's a name that's quite general and is already a macro in Rust, but something like `log_if_env` or something along those lines?

**Comment by svmorris** [comment]
> I'm just concerned about polluting envs with even more environment variables.

I mean that is all the more reason to have choice. It is not really something that concerns me, especially if its not global but just `CODECTR_DEBUG=true ./app`, but I understand that not everyone agrees with that.

> probably wouldn't call the function dbg as that's a name that's quite general and is already a macro in Rust

I'm not hugely knowledgeable about rust, but isn't codectrl its own namespace or something? Like in python it would be `codectrl.dbg()`. I mean if it somehow interferes then `log_if_env` is perfectly fine, but if possible id rather have it short and simple.

**Comment by STBoyden** [comment]
> I mean that is all the more reason to have choice. It is not really something that concerns me, especially if its not global but just CODECTR_DEBUG=true ./app, but I understand that not everyone agrees with that.

Yeah something like that could be quite nice yeah, I will do that.

> I'm not hugely knowledgeable about rust, but isn't codectrl its own namespace or something? Like in python it would be `codectrl.dbg()`. I mean if it somehow interferes then `log_if_env` is perfectly fine, but if possible id rather have it short and simple.

It would be yeah, but I'd rather that it would be explicit in the fact that it uses/reads/depends on an environment variable. As I said before, `dbg` seems too general as a name to me personally. We could have the envvar as `CODECTRL_DEBUG=true` as you said, and have the function called `log_if_env` or something similar that is explicit to the fact that it depends on an envvar.

**Comment by STBoyden** [comment]
It might be worth having a repository that contains a schema for all the language loggers so that future ones, hopefully even ones not written by us, can follow it and be consistent with the others.

**Comment by STBoyden** [comment]
I believe this is now done? @svmorris
