### ISSUE TITLE
Skipping logs

### ISSUE THREAD

**Issue by svmorris** [Authentura/codectrl#27]
While using codectrl I came across an issue where some logs would not show up in the gui. There are no errors or warnings present in either the gui or the console.
After some debugging I think It only happens when there are many requests hitting the server in very quick succession.

Trying to run the following code:
```py
    for i in range(0, 100):
        codectrl.log(i)
```
In the gui I get a few missed numbers:
![Screenshot from 2022-02-24 13-46-12](https://user-images.githubusercontent.com/46561460/155536097-debbe96b-b963-48b3-a719-ff8a83d02328.png)

The same behaviour is present with both the python and the nodejs loggers, thus I think its either a codectrl problem or something with my operating system.

**Comment by STBoyden** [comment]
I will try to recreate this issue using the Rust logger and the Python one to see if it's logger-specific or CodeCtrl itself.

Also, I know this was a bit ago but can you remember whether or not you had another CodeCtrl instance open?

**Comment by svmorris** [comment]
No. I don't, but that is a good point.
Ill try do some more tests today or tomorrow and get back to you :slightly_smiling_face:

**Comment by STBoyden** [comment]
Thank you. The reason why I ask is that I explicitly set `REUSE_PORT` on by default in the server portion of the code. I noticed that when one or more instances are open, the logs seem to be distributed to each instance at random. I will likely disable this, regardless of whether it is the cause of this issue or not.

**Comment by svmorris** [comment]
That's fine. If you use reuse sockets though you should probably make sure the app is not already running when you launch. Could cause confusion :sweat_smile:

**Comment by STBoyden** [comment]
Agreed. Will have to implement some sort of check, or just disable it outright

**Comment by STBoyden** [comment]
Just tested this with the Python logger and the Rust logger, I don't seem to be getting the same issue. Possibly indicative of the multiple instances?

As I said earlier, I may either remove that ability or have a sort of check to prevent this confusion again if it's not your operating system being the cause.

**Comment by STBoyden** [comment]
Closed because I don't think this has been replicated since.
