### ISSUE TITLE
Consider adding CodeCTRL to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [Authentura/codectrl#53]
Hey @STBoyden @CollinJoseph @svmorris, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by STBoyden** [comment]
Will do! :)

**Comment by STBoyden** [comment]
Submitted PR https://github.com/SeaQL/sea-orm/pull/1015 :)

**Comment by billy1624** [comment]
Hey @STBoyden, thanks for the love and support on SeaORM :))
