### ISSUE TITLE
Contributing.md file missing!

### ISSUE THREAD

**Issue by Sidd2024** [Authentura/codectrl#62]
According to hacktoberfest guidelines there should be contributing.md present in projects participating in hacktoberfest.
please assign this task to me!

**Comment by STBoyden** [comment]
Aha sorry mate, was just about to add one. If you'd like, I can push my current version and you can continue on with it?

**Comment by Sidd2024** [comment]
yeah sure no problem...

**Comment by STBoyden** [comment]
Done. Feel free to work on it

**Comment by Sidd2024** [comment]
here, I've raised a PR #63

**Comment by STBoyden** [comment]
Closed on #63
